#!/bin/bash

# Git Aliases and Functions
alias ga='git add .'
alias gc='git commit -m'
alias gac='ga && gc'
alias gp='git push'
alias gcl='git clone'
alias gpp='git pull'

# Personal functions
gacp () {
	git add .
	git commit -m "$1"
	git push origin master
}

gcll () {
	git clone "https://github.com/$1/$2.git"
}
