#!/bin/bash

# Alias definitions. This chunk of code is required in ~/.bashrc to run this file
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
#
# if [ -f ~/.bash_aliases ]; then
#     . ~/.bash_aliases
# fi

# Git Aliases and Functions
alias ga='git add .'
alias gc='git commit -m'
alias gac='ga && gc'
alias gp='git push'
alias gcl='git clone'
alias gpp='git pull'
alias gs='git status'

# Personal functions
gacp () {
	git add .
	git commit -m "$1"
	git push
}

gcll () {
	git clone "https://github.com/$1/$2.git"
}

# Using bash_aliases as a bashrc
bind TAB:menu-complete
bind '"\e[Z":menu-complete-backward'

#ctags for js
alias ctagsjs='ctags --options=NONE --options=${HOME}/.ctagsrc -R .'
