" Indentation and Spacing
set autoindent
set list
set listchars=tab:\>\ 
set tabstop=3
set shiftwidth=3

" Searching and Casing
set hlsearch
set incsearch
set ignorecase
set smartcase
set wildmenu

" Quality of Life
set nocompatible
set autoread
set backspace=indent,eol,start
set linebreak
set mouse=a
set number
set scrolloff=4
set title

" Status Line
set laststatus=2
set statusline= "Clear status line
set statusline+=Current\ File:\ %t%y\ %M\  "File path relative to current directory
set statusline+=%=
set statusline+=Line\ %2l\ of\ %L,\ Column\ %-2c\ %2p\ Percent "Position in the file

" Syntax and Display
syntax enable
colo elflord
set background=dark
set cursorcolumn
set cursorline
hi Search ctermbg=Cyan
hi Search ctermfg=Black
hi clear CursorLine
hi default link CursorLine CursorColumn
hi CursorColumn gui=NONE cterm=NONE ctermbg=233
hi SpecialKey guifg=grey ctermfg=16
hi SpecialKey guifg=grey ctermfg=235

"Macros
let @b="mx?\\/\\*\<CR>2d /\\*\\/\<CR>2d `x"
let @c="^i//\<Esc>"
let @i=":set paste\<CR>i<!DOCTYPE html>\<CR>\<Tab><head>\<CR>\<Tab>\<Tab><title>Welcome</title>\<CR>\<Tab>\<Tab><link rel=\"stylesheet\" href=\"./styles.css\">\<CR>\<Tab></head>\<CR>\<Tab><body>\<CR>\<Tab>\<Tab>\<CR>\<Tab>\<Tab><script src=\"scripts.js\">\<CR>\<Tab></body>\<CR></html>\<Esc>:set nopaste\<CR>kkk$"
let @m="A*/\<Esc>2h"
let @n="^i/*\<Esc>"
let @z="^2d "
